# Generated by Django 3.0.7 on 2020-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pupdate',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
